.codeclimate.yml
Gemfile
Gemfile.lock

- Import Devise token auth gem using https as code climate suggests.
- Remove `codeclimate.yml` file. An issue https://github.com/rootstrap/rails_api_base/issues/91 is opened to discuss and create a new `codeclimate.yml` file with the proper configuration.

Import devise token auth using https

---

config/initializers/carrierwave.rb

* [Trello Card #ENHACEMENT]()
---
* This PR remove checking from cucumber env since it's not being used either the gem is included in the gemfile
---
* @MaicolBen
* @matiasmansilla1989
* @santiagovidal 
---
*
---
---
Options: (None, little, Medium, Risky)
* little
---
---

remove unnecessary check for cucumber env

---

app/controllers/api/concerns/act_as_api_request.rb
spec/requests/api/v1/sessions/create_spec.rb

Resolves #101
This PR handles this issue #101 overriding the render_error method from devise (added by @MaicolBen in this PR https://github.com/lynndylanhurley/devise_token_auth/pull/989 ) to be more consistent with the way the API render the errors or an error

Override devise render error to be consistent with the API

---

app/controllers/api/v1/api_controller.rb

On testing, don't handle Exception on the controllers and
let it bubble up.

Remove Exception handler on controllers for test

---

Gemfile.lock
app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/passwords_controller.rb
app/controllers/api/v1/registrations_controller.rb
app/controllers/api/v1/sessions_controller.rb
config/initializers/carrierwave.rb
spec/factories/spec.rb
spec/models/user_spec.rb
spec/spec_helper.rb

This PR includes:
- Fix `ActAsApiRequest` import, sometimes depending on the order of the import, this is something that breaks
- Resolves #111 (use `FactoryBot.lint` instead)
- Enable user pending test 
- After upgrading ruby, `fog-aws` [wasn't imported correctly by carrierwave](https://github.com/fog/fog/issues/3429), so I declared the provider

Enable pending test, fix fog-aws import & use FactoryBot.lint

---

config.reek
config/application.rb
spec/spec_helper.rb

Instead of tests and fixtures, we use `rspec` and factory bot, so I changed the default generators, useful for model generation. 
Also, I removed a rspec filter we don't use

Change default generators

---

config/initializers/figaro.rb

When projects start with application.yml from the example it fails because figaro required vars. Adding empty strings prevent it to fail when you don't use them at the start

Prevent app failure because figaro required vars

---

app/controllers/api/v1/sessions_controller.rb

This method was left there by accident. We can remove it now.

Remove unused json_request? method

---

app/controllers/api/v1/api_controller.rb

Solves https://github.com/rootstrap/rails_api_base/issues/134
The proposed solution is to use the exception's message to check if the API should return a 404.

Return 404 when RecordNotFound happens in a view

---

spec/requests/api/v1/sessions/destroy_spec.rb

The idea here is to improve the sign out specs by checking if the token was deleted. I also added a test for the case when no token is received.
Credit to @leandrodzp, who did it first in this PR https://github.com/leandrodzp/target2/pull/11

Sign out spec now checks if the token was destroyed

---

config/initializers/new_framework_defaults.rb

This PR is intended to fix an issue with the new_framework_default initializer which is supposed to have the configuration to make sure that a belongs_to association validates the presence of the record by default. 
Right now as we check it with @jdrosales17  and @JuanfraM this is not working and with this change we fix that issue

fix default belongs_to presence validation

---

spec/models/user_spec.rb

* Change to RSpec 3 syntax some specs that used RSpec 2. 
The gem [transpec](https://github.com/yujinakayama/transpec) was used to ensure that there is no missing RSpec 2 examples.

Convert to rspec 3 some rspec 2 specs

---

.rubocop.yml
spec/requests/api/v1/passwords/create_spec.rb
spec/requests/api/v1/sessions/destroy_spec.rb
spec/requests/api/v1/users/create_spec.rb

Seems like it's something we already decided about in the [tech guides](https://github.com/rootstrap/tech-guides/tree/master/ruby#single-line-blocks), so I'm adding the corresponding rule here.
Personally, I agree it's nicer to user braces when chaining. Example:
```ruby
expect do
run_job
end.to change(User, :count).by(1)
expect {
run_job
}.to change(User, :count).by(1)
```

Enforce the usage of braces for chaining

---

Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

With @santib, we removed Database Cleaner in The List project, which has Rails 5.2 and some Capybara tests, and everything worked fine (all the tests passed).
As @santib explains in https://github.com/rootstrap/rails_api_base/issues/139, from Rails 5.1.5 this gem is not needed anymore, so this PR removes the use of it.

Remove Database Cleaner

---

app/controllers/api/v1/registrations_controller.rb
app/controllers/api/v1/sessions_controller.rb

This PR include:
- Turn `sign_up_params` and `render_create_success ` methods  into private methods in  `RegistrationsController `
- Turn `resource_params` method into private method in `SessionsController `
There is no reason to keep these methods public in the controllers

Turn methods private in RegistrationsController and SessionsController

---

CODEOWNERS
README.md

CODEOWNERS file is added. 
This way users can be set as responsible for the project's code, and they will be automatically requested for review when a PR is opened.

Add CODEOWNERS file

---

.circleci/config.yml
.codeclimate.yml
lib/tasks/rails_best_practices.rake

Since CodeClimate supports Reek plugin we are migrating `reek` check from CircleCI to CodeClimate.
- Now in `.circleci/config.yml` only includes `rails_best_practices` check which is the only linter that isn't supported by CodeClimate.
- Now `.codeclimate.yml` includes `brakeman` , `rubocop` and  `reek`.
- We still keep `code_analysis` rake task in order to run it locally.

Enhancement - Migrate linters to CodeClimate

---

.circleci/config.yml
.codeclimate.yml
lib/tasks/rails_best_practices.rake

- Remove code analysis tools from CodeClimate since we are having issues with the channels for `Rubocop`, `Reek` and `Brakeman` plugins. At the moment there is a mismatch between the plugins version in CC and the versions in the Api Base Gemfile.
- run `RAILS_ENV=test bundle exec rake code_analysis` as a CircleCI step.
Note: This is a temporary workaround until we find a better way or when we have more plugins versions available in channels supported by CodeCimate.

Move back code_analysis task to Circle CI

---

app/admin/admin_user.rb

Remove autogenerated content from ActiveAdmin

---

.circleci/config.yml
bin/rails
bin/rake
bin/setup
bin/yarn
config/application.rb
config/boot.rb
config/cable.yml
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/application_controller_renderer.rb
config/initializers/assets.rb
config/initializers/content_security_policy.rb
config/initializers/new_framework_defaults_6_0.rb
config/puma.rb

This PR fixes an existing issue with the migration to rails 6 that was previously made. Even though the project was using rails 6, action_text was not available. After running the command `rails app:upgrade`, the command to install action_text becomes available (`action_text:install`).
All of the changes were made by the `rails app:upgrade` command (even the changes in comments)

Fix rails 6 migration issues

---

config/environments/staging.rb

It's up to discussion, but I think it's a bad idea to have a staging env that differs from production. 
https://12factor.net/dev-prod-parity

Remove staging environment

---

app/models/user.rb
db/migrate/20161011151353_devise_create_users.rb
db/schema.rb

Devise module and column `Rememberable` removed from `user` model and table.
Issue: https://github.com/rootstrap/rails_api_base/issues/171

Issue fix: Rememberable devise module removed

---

config/routes.rb

* Removed `api/v1/status` from users scope in routes.

Remove status route from users scope

---

spec/models/user_spec.rb
spec/rails_helper.rb
spec/requests/api/v1/status_spec.rb

Test coverage should reveal which lines of code are we missing to test, it shouldn't measure that on the tests itself.

Exclude specs when measuring test coverage

---

.circleci/config.yml

* N/A
---
* This PR moves the `code_analysis` task before running the tests in the circleci pipeline. This is because the `code_analysis` takes less time to execute than the tests. This can potentially save computing time in circleci to allow other workflows to run.

Move tests down in the pipeline

---

Dockerfile
docker-compose.yml

* This PR improves the docker support. What happened before, was that  when developing inside the container, the following problems occured:
1. The container would start using the bundler version 1.x
2. Gems would stay outdated in some cases
* Also This PR makes the final image smaller. I took some ideas from [thoughtbot docker examples](https://thoughtbot.com/blog/rails-on-docker) to make the improvements.
---
* To execute the rails commands, there are 2 ways:
1. `bin/rails ...`
2. `bundle exec rails ...`
* Directly calling `rails` uses the bundler version 1.x and an error message will appear, signaling that a bundler version 2 or greater is needed.

Improve dockerfile

---

app/models/setting.rb
app/models/user.rb
db/schema.rb
lib/tasks/auto_annotate_models.rake
spec/factories/settings.rb
spec/factories/users.rb
spec/models/user_spec.rb

- This PR fixes `auto_annotate_models` task. It was not triggering after executing `bin/rails db:migrate`. Now it does
- Adds settings model timestamp to schema. (Seems like `db:migrate` wasn't run previously)
- Fix annotations

fix models auto annotation task

---

Gemfile
Gemfile.lock
package.json
yarn.lock

* Fix dot-prop and serialize-javascript security problem
[CVE-2020-7660](https://github.com/advisories/GHSA-hxcc-f52p-wc94) **high severity**
**Vulnerable versions**: < 3.1.0
**Patched version**: 3.1.0
serialize-javascript prior to 3.1.0 allows remote attackers to inject arbitrary code via the function "deleteFunctions" within "index.js".
An object such as {"foo": /1"/, "bar": "a\"@__R-<UID>-0__@"} was serialized as {"foo": /1"/, "bar": "a\/1"/}, which allows an attacker to escape the bar key. This requires the attacker to control the values of both foo and bar and guess the value of <UID>. The UID has a keyspace of approximately 4 billion making it a realistic network attack.
The following proof-of-concept calls console.log() when the running eval():
eval('('+ serialize({"foo": /1" + …

fix dot-prop and serialize-javascript high severity issues

---

config/application.rb

- Removed `{project_root}/lib` directory from the autoload paths
We can have a `{project_root}/app/lib` folder for the `.rb` files.
Autoloading, reloading and eagerloading work by default using zeitwerk mode, so there's no need to extend `autoload_paths`.
Also, this is the recommended way according to [this comment](https://github.com/rails/rails/issues/37835#issuecomment-560075069).
- opt-out autoloadable files from `$LOAD_PATH`
> Autoload paths are added to `$LOAD_PATH` by default. However, Zeitwerk uses absolute file names internally, and your application should not issue require calls for autoloadable files. 
Reference: [here](https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#%24load-path)
---
For more context, Zeitwerk mode explained …

Remove lib directory from the autoload paths

---

.circleci/config.yml

**In this PR:**
The reason behind this is that the developer should always commit these files and therefore if by any chance the dev forgets to do so, then the build should fail.
[source](https://thoughtbot.com/blog/keep-autogenerated-files-synced)
To see this in action please check the following builds in another project where I tested this:
- https://app.circleci.com/pipelines/github/rootstrap/takion-api/53/workflows/8fbcce71-3c86-4ed6-a493-f553089df7e9/jobs/54
- https://app.circleci.com/pipelines/github/rootstrap/takion-api/51/workflows/a845dc4d-16d5-4853-abb0-3f19162788c6/jobs/52

Enhancement: Add file tracking checks to CI

---

.circleci/config.yml
README.md

**In this PR:**
**Description:**
As @pablanco suggested, we could be adding this key to the ENV variables of the project.
This will not only improve security, but also when cloning this repository, if the key is not set, then the CI build will fail. So in a way we are enforcing the devs to set their own key

Enhancement: set CC_TEST_REPORTER_ID as a env key in CircleCI

---

app/controllers/api/concerns/act_as_api_request.rb
spec/requests/api/v1/status_spec.rb

Clients use the Content-Type header to tell the server what type of data
has been sent. Hence there is no need for the server to disallow GET or
HEAD requests. More info on how the Content-Type header is/should-be used for
requests [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#:~:text=the%20client%20tells%20the%20server%20what%20type%20of%20data%20is%20actually%20sent) and [here](https://tools.ietf.org/html/rfc7231#section-3.1.1.5).
Updated status_spec to match this behavior.

Check Content-Type header only when a payload is sent

---

.circleci/config.yml

I have found PRs that change the annotations on files that are not necessarily changed in that particular PR, in fact, I have made the mistake of uploading pull requests without running the annotate 😞 . So in order to prevent that kind of thing happen, I extended the check of changed files to see if running annotate changed any (which shouldn't).
FYI: I placed this check after all the other ones as the build is less common that someone forgot to run `annotate` than to have failing tests or have code style errors.
Added Time to the build: `1 second`

Enhancement: check if annotate was run in CircleCI

---

README.md
config/initializers/rspec_api_documentation.rb

This PR changes the _apiary_ link at `README.md` because was outdated and was not using the docs generated in #269

Change apiary link in readme

---

app/controllers/api/v1/api_controller.rb

In this PR it is changed the way parameters are passed to the logger. The reason behind this can be found [here](https://guides.rubyonrails.org/debugging_rails_applications.html#impact-of-logs-on-performance).
```
Logging will always have a small impact on the performance of your Rails app, particularly when logging to disk. Additionally, there are a few subtleties:
Using the :debug level will have a greater performance penalty than :fatal, as a far greater number of strings are being evaluated and written to the log output (e.g. disk).
Another potential pitfall is too many calls to Logger in your code:
logger.debug "Person attributes hash: #{@person.attributes.inspect}"
In the above example, there will be a performance impact even if the allowed output level doesn't include debug. The …
```

Enhancement: pass logger parameters as blocks

---

app/channels/application_cable/channel.rb
app/channels/application_cable/connection.rb

Rails generates these files by default. (https://guides.rubyonrails.org/action_cable_overview.html#channels)
I think we should keep them, as some gems could expect you to have them.
These files were removed in this PR(https://github.com/rootstrap/rails_api_base/pull/127)

ApplicationCable

---

.rubocop.yml
app/controllers/api/v1/api_controller.rb
app/controllers/application_controller.rb
config/application.rb
config/environments/development.rb
spec/requests/api/v1/settings_spec.rb

Api only apps won't need all controller modules used in normal applications,
for instance: ViewPaths, Layouts, Templates, and so on. Moreover, api only apps
won't need all middlewares used in normal applications, for instance:
MethodOverride (used to override the HTTP verb when passing a hidden
field in form submissions), ContentSecurityPolicy (which is a browser-only thing), and so.
One consideration: Devise controllers will always
inherit from ApplicationController, hence we still need to use the
ActAsApiRequest concern in Devise controllers. This is because Devise is shared
between the API-only app and the admin panel.
_Branched off from #250_

Using Rails in api_only mode

---

README.md

Right now when configuring the app with the default **DOCKER** credentials results in an error:
```
could not connect to server: Connection refused
Is the server running on host "localhost" (127.0.0.1) and accepting
TCP/IP connections on port 5432?
```
Because we should point to `db` host in the `database.yml`
Also, postgres now requires the default username and password, so right now the result is:
```
fe_sendauth: no password supplied
Couldn't create 'a-price-for_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: fe_sendauth: no password supplied
```
The fix for that is to add `postgres` and `postgres` as `username/password` for the DB

Update Readme to include database configuration with docker-compose

---

README.md

* Ticket: NO TICKET
---
Just fixing gem name
---
* None

Fix typos on RSpec gem name

---

.gitignore
.irbrc
.pryrc

By printing the env in the rails console we can avoid mistakes in production. Added the code both for `irb` and `pry`
https://twitter.com/_swanson/status/1346851840944730112/photo/1
https://gist.github.com/Intrepidd/af2bb4ed825817ecb044a5e93fc52f4d

Add env to the rails console

---

app/controllers/application_controller.rb
spec/rails_helper.rb

- This PR's aim is to fix a recurring issue when using the Active Storage Disk Service when developing locally and also testing. Example of the issue at the preview.
---
* https://stackoverflow.com/questions/71860516/activestoragecurrent-host-is-deprecated-how-can-i-use-activestoragecurrent
---

ActiveStorage Current

---

.github/workflows/ci.yml
lib/tasks/code_analysis.rake

---
This PR splits the tests and linters to run parallel
---
*
---
---
*
---

split tests and linters

---

app/controllers/application_controller.rb

This was wrong, and we weren't making sure that our endpoints were being authorized

Fix Pundit setup

---

spec/rails_helper.rb

When running requests specs, Rails is automatically clearing all the `ActiveSupport::CurrentAttributes` including `ActiveStorage::Current`, so when doing `something.file.url` after the request, it failed with
```
ArgumentError:
Cannot generate URL for tree.fbx using Disk service, please set ActiveStorage::Current.url_options.
```
this is the place where Rails clears the attributes:
https://github.com/rails/rails/blob/main/activesupport/lib/active_support/railtie.rb#L49-L50
so with this change we are automatically setting the `ActiveStorage::Current.url_options` right after the request was performed.

Fix ActiveStorage::Current in request specs

---

.github/workflows/update_knapsack_report.yml
docs/ci.md

Update Knapsack workflow
If the branch exists or the PR is already created the workflow will fail.
In your repository settings -> actions -> general ->  Workflow permissions we need to allow read / write permissions and mark the option allow Github action to create Pr, other case the workflow will fail.
---
---
*
---
The PR looks like this

Knapsack ci workflow updates

---

bin/helpers.rb
bin/setup
bootstrap.sh

* N/A
---
When using Docker, the setup script was failing / not working as expected. The `running_with_docker?` method checks the env var `DOCKER_ENABLED=true`, but the default is `false`. This adds a rewrite of that value if bootstrapping with Docker. I also added a utility method for the bootstrap script since this uses `sed` again, necessitating the OS check.
---
* I'm new here, so I'm not sure if we want to load dotenv in all the bin scripts that reference `running_with_docker?`, but it seems like it might be worthwhile, if anyone runs those scripts in isolation.
---
N/A
---
N/A
---
N/A

Update docker env var during bootstrap

---

docs/feature_flags.md

https://www.notion.so/rootstrap/Documentar-ac6a53fb2ec64aebb818bb9023c8ad11?pvs=4
---
Feature flags documentation
---
* -
---
---
* no
---
👁️

Add feature flags documentation

---

.reek.yml
app/models/admin_user.rb
app/models/application_record.rb
app/models/concerns/ransackable.rb
app/models/setting.rb
app/models/user.rb

---
This [PR](https://github.com/rootstrap/rails_api_base/pull/483) introduced new version of Ransack gem (4.0.0). This introduced some breaking changes and prevents the use of current ActiveAdmin sections.
This [article](https://rogodev.com/ransack-40-allowlist-changes) explains the reason and how to fix the issue.
Let me know if this is the best possible solution. 😄
* High
---

Hotfix Ransack 4.0.0

---

.github/workflows/ci.yml

Remove unnecessary version since it uses the `.ruby-version` by default

Remove ruby version from CI

---

app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/health_controller.rb
config/routes.rb

Having the `status` action defined in `ApiController` which is then inherited by other controllers, was causing a very strange bug related to the [wrap_parameters](https://api.rubyonrails.org/classes/ActionController/ParamsWrapper.html) Rails feature.
In order to reproduce go to the `main` branch, perform the following changes to force the execution of the wrap_parameters feature:
```diff
+++ spec/requests/api/v1/users/update_spec.rb
@@ -9,14 +9,14 @@ describe 'PUT api/v1/user/' do
before { subject }
context 'with valid params' do
-    let(:params) { { user: { username: 'new username' } } }
+    let(:params) { { username: 'new username' } }
it 'returns success' do
expect(response).to have_http_status(:success)
end
it 'updates the user' do
-      expect(user.reload.username).to …
```

Fix obscure bug

---

app/assets/stylesheets/application.css
app/views/layouts/application.html.erb
config/application.rb
config/environments/development.rb

Revert https://github.com/rootstrap/rails_api_base/pull/253/files. We aren't getting any benefit from it.
Actually, our app is not api only, we still are loading middlewares because they are needed for ActiveAdmin.
Every Rails app comes with one https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/app/views/layouts/application.html.erb.tt
It will be helpful if we ever want to develop an HTML page outside the admin site.
We don't want Arctic Admin styles to leak into application CSS, for that reason, application CSS should go into the `app/assets/stylesheets/application/` directory

Make api base ready for fullstack

---

.github/CONTRIBUTING.md
README.md
app/controllers/api/concerns/act_as_api_request.rb
app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/health_controller.rb
app/controllers/api/v1/passwords_controller.rb
app/controllers/api/v1/registrations_controller.rb
app/controllers/api/v1/sessions_controller.rb
app/controllers/api/v1/settings_controller.rb
app/controllers/api/v1/users_controller.rb
config/initializers/inflections.rb
spec/requests/api/v1/users/show_spec.rb
spec/routing/registrations_routing_spec.rb
spec/routing/sessions_routing_spec.rb
spec/routing/user_routing_spec.rb

Inflect API

---

.github/workflows/ci.yml
.rubocop.yml
Gemfile
Gemfile.lock
spec/features/admin/sign_in_spec.rb
spec/spec_helper.rb

* [Ticket Notion](https://www.notion.so/rootstrap/Add-feature-system-specs-to-the-admin-site-in-the-Rails-API-Base-just-a-few-489ec65c7c084394918edb1bb4a66045?pvs=4)
---
- Add capybara
- Test admin sign-in

Add capybara

---

config/initializers/rswag_api.rb
config/initializers/rswag_ui.rb

* [Ticket Resolve DEPRECATION WARNING related with swagger gems](https://www.notion.so/rootstrap/Resolve-DEPRECATION-WARNING-related-with-swagger-gems-2c1a20f30a8c4ee789e6b0a099c895ac?pvs=25)
---
* Replace deprecated methods for rswag gems
---
```shell
17:10:57 web.1  | DEPRECATION WARNING: swagger_root= is deprecated and will be removed from rswag-api 3.0 (use openapi_root= instead) (called from block in <main> at /Users/samirtapiero/Backend/rails_api_base/config/initializers/rswag_api.rb:8)
17:10:57 web.1  | DEPRECATION WARNING: Rswag::Ui: WARNING: The method will be renamed to "openapi_endpoint" in v3.0 (called from block in <main> at /Users/samirtapiero/Backend/rails_api_base/config/initializers/rswag_ui.rb:12)
```
---

Fix deprecation warnings for Swagger

---

.rubocop.yml

Fix the following warning:
`Warning: no department given for RescuedExceptionsVariableName.`

Fix rubocop warning

---

.github/dependabot.yml

Also make dependabot keep GHA actions (e.g. actions/checkout) up to date, and JS packages (package.json and yarn.lock) up to date

Also keep GHA actions and JS packages up to date

---

.github/dependabot.yml

I made a mistake and it should have been `npm` not `yarn in the `dependabot.yml`

Fix dependabot package-ecosystem for yarn

---

config/routes.rb

Small fix on routes file.
Need to force JSON scope to prevent Devise routes from defaulting the request format to `*/*`

Ensuring consistency of API routes

---

app/controllers/api/v1/passwords_controller.rb

Related to https://github.com/lynndylanhurley/devise_token_auth/issues/1536
When running the tests, I get some errors like this one:
```
$ DOCKER_ENABLED=true ./bin/rspec
$ ./bin/rspec
1) PUT api/v1/users/passwords/ with valid params returns a successful response
Failure/Error: get edit_user_password_path, params:, headers: auth_headers
ActionController::Redirecting::UnsafeRedirectError:
Unsafe redirect to "http://127.0.0.1:3000?access-token=2LGXSO3yWsPxPWCyGml-wA&client=MJDpDQiAegGCGFWy3qDS_A&client_id...", pass allow_other_host: true to redirect anyway.
```
Rails 7 raises `ActionController::Redirecting::UnsafeRedirectError` for unsafe `redirect_to` redirects. https://github.com/rails/rails/commit/c3758a71af949db849d5b7f176677653e4e4fae9
Adding the `allow_other_host` option for the …

Fix DeviseTokenAuth gem UnsafeRedirectError

---

spec/requests/api/v1/concerns/impersonation/hooks_spec.rb

Skip OPENAPI in hooks spec.
---
The hooks spec mocks an endpoint, causing OPENAPI to fail. Since we don't require API documentation for a mocked endpoint, this PR skips OPENAPI docs generation in hooks_spec

Skip OPENAPI in hooks_spec

---

app/objects/impersonation/headers.rb
config/initializers/rack_cors.rb

- Add the impersonated header to rack_cors. We need this header to be exposed in the headers response to allow for impersonation.
- Fix a small issue in the `build_impersonation_header` method. The @user does not exist when we make the first request to `POST /impersonations`

Add impersonated header to rack_cors

---

README.md
db/schema.rb

* The `schema.rb` version is not updated with our current `rails version`
* If you run `bundle exec rspec` before running `yarn install`, you get two failing tests

Add missing change in the `schema.rb` and re-order steps in the "How to use" section of the `README.md`

---

.rubocop.yml
app/controllers/api/concerns/act_as_api_request.rb
app/controllers/api/v1/api_controller.rb
app/controllers/api/v1/passwords_controller.rb
app/controllers/api/v1/registrations_controller.rb
app/controllers/api/v1/sessions_controller.rb
spec/requests/api/v1/concerns/impersonation/hooks_spec.rb
spec/requests/api/v1/registrations/create_spec.rb
spec/requests/api/v1/sessions/create_spec.rb
spec/requests/api/v1/status_spec.rb
spec/requests/api/v1/users/show_spec.rb
spec/requests/api/v1/users/update_spec.rb
spec/support/retry/message_formatter.rb
spec/support/shared_examples/requests/forgery_protection_disabled.rb

Many minor improvements:
1. Add `rubocop-rspec_rails` to `.rubocop.yml` because it was not being loaded
2. Don't use `as: :json` for GET requests in the specs because they get converted to POST
3. Simplify `ActAsAPIRequest` concern
4. Unify response format when rendering errors with `render_error`
5. Add specs for sign up
6. Improve message when reporting an intermittent test
7. Fix forgery protection tests

Misc improvements

---

Gemfile
Gemfile.lock

* Change `devise_token_auth` in the Gemfile so it points to `RubyGems`, that it already has the last version
* Upgrade `bundler` version to the last one

Change reference of `devise_token_auth` in the Gemfile

---

app/controllers/application_controller.rb
config/storage.yml
lib/active_storage/service/disk_with_host_service.rb
spec/rails_helper.rb

---
This PR is for having the fix for the issue when using Active Storage Disk Service in development and test environments but without using the `ActiveStorage::SetCurrent` concern. Also this fix applies now for `APIController`. 
This solution was seen here https://github.com/rails/rails/issues/40855#issuecomment-1970876302
---
*
---
---
*
---

Config ActiveStorage Current without using concern

---

bin/helpers.rb

Now, if `Docker` is off, rails commands will still work. Fixes #753

Fix Docker usage

---

Dockerfile.dev
README.md

---
- There is this error when running `bin/rspec .`:
```
Failure/Error: raise AssetNotFound, message unless unknown_asset_fallback
ActionView::Template::Error:
The asset "active_admin.js" is not present in the asset pipeline.
```
- This is fixed by adding the `RUN yarn build`
- Also added a link to the docker docs in the readme
---
*
---
---
*
---

Fix missing assets when running specs and add link to docs

---

.github/workflows/cd.yml
docs/cd_with_aws.md

* [Promoters Ticket](https://www.notion.so/rootstrap/Implement-CD-process-in-Github-Action-for-rails_api_base-e5f2a3e9d1224254988ba864a46355a8)
---
To streamline app deployment, enhancing team efficiency. Utilizing GitHub Actions centralizes processes, aiding devs familiar with the repo.
[GitHub CD Documentation](https://www.notion.so/Github-CD-Documentation-32e4e1cff56647e7af2326e6756dee05?pvs=21)

Add CD with github actions

---

Gemfile.lock

Dependabot's [PR](https://github.com/rootstrap/rails_api_base/pull/770) removed the Ruby platform. This change causes differences in our Gemfile.lock when installing gems locally in a non-linux architecture

Add missing platforms

---

Dockerfile.dev
bin/docker-entrypoint
bin/fullstack.rb
bin/web
docker-compose.test.yml
docker-compose.yml
docs/docker.md
docs/fullstack.md

- Remove the `BUNDLE_PATH` env variable from `Dockerfile.dev`. This variable was changing the path where bundler is installing the gems and slowing the volume mount Docker process. Also generating some conflicts with the `fullstack.rb` script and gems were installed twice, in different locations.
- Update the entrypoint script so it runs the `db:test:prepare` command when `RAILS_ENV=true`
- Replace the Docker Compose watch feature with a bind mount volume so Rails generators and scripts are able to create files on the host
- The watch mechanism does nothing if the path it is watching is already included in a volume. `WARN[0064] path 'Gemfile' also declared by a bind mount volume, this path won't be monitored! `

Fix fullstack script and Rails generators with Docker

---

.github/workflows/ci.yml

We currently have an intermittency in the CI https://github.com/rootstrap/rails_api_base/actions/runs/11445963325/job/31844133037#step:10:18 that seems to be caused by a race condition when generating the secret key base in test env. What Rails does it create a txt file with the value, but our first command that triggers it is the setup of our databases in parallel.
With this PR we make sure that the secret is generated only once, and then it will be used by all the processes running in parallel.

Fix race condition

---

config/initializers/colorized_logger.rb
config/initializers/lograge.rb

Taken from https://gist.github.com/kyrylo/3d90f7a656d1a0accf244b8f1d25999b
Improves logs legibility by colorizing them by the log level
Another additional gem that may be worth adding (but requires more manual setup) is https://github.com/mechanicles/colorize_logs
BEFORE:
AFTER:

Colorize logs in dev

---

.github/workflows/ci.yml
docs/ci.md

This PR adds a new Github action that builds the Production Dockerfile.

Add docker job to CI

---

bin/docker-entrypoint

When running commands with Docker, I noticed the following error
```
./bin/docker-entrypoint: line 8: [: ==: unary operator expected
```
This PR fixes the syntax error in the shell script.

Fix Docker entrypoint syntax error

---

Dockerfile
Dockerfile.dev

Example error: https://github.com/rootstrap/rails_api_base/actions/runs/12769411348/job/35591931172

Fix Dockerfile

---

app/assets/stylesheets/active_admin.scss
config/initializers/assets.rb

---
- Icons were not displayed in Active Admin.
---
*
---
---
*
---

Fix icons not displayed in ActiveAdmin

---

.github/workflows/ci.yml
app/controllers/api/v1/health_controller.rb

---
Changes Docker image caching in CI to use GHA Cache. This reduces build time by ~20 seconds if cached image exists (tested with only code changes). Additionally, this already handles compression, reducing the size of cache entries.
You can check the cache entries generated for this PR (last two commits) [here](https://github.com/rootstrap/rails_api_base/actions/caches?page=2&query=branch%3Arefs%2Fpull%2F960%2Fmerge).
---
*
---
---
*
---

Improve Docker CI Cache

---

bin/release.sh
heroku.yml

When using the `heroku.yml` to deploy apps with the container stack on Heroku, the release script is not being executed. This PR fixes the issue by adding the script into the `heroku.yml` file.
Note: Migrations are executed as part of the `docker-entrypoint` script, so we don't need to run them during the release phase (just like Rails does in [this template](https://github.com/rails/rails/blob/main/railties/lib/rails/generators/rails/app/templates/docker-entrypoint.tt#L12))

Use release script when deploying with containers

---

Procfile.dev

Without this change, the PORT ENV VAR is not respected when running `bin/dev`

Use PORT ENV VAR instead of hardcoding it
