- .codeclimate.yml
- Gemfile
- spec/requests/api/v1/sessions/create_spec.rb
- spec/requests/api/v1/sessions/facebook_spec.rb
- spec/requests/api/v1/users/create_spec.rb
Resolves #88
Resolves #91
- Skipped rubocop in db because it complains `Assignment Branch Condition size for change is too high.` for big  `change` methods in migrations
- Skipped flog in spec/config/db because it complains for complex methods in migrations, specs and initializers
- Skipped duplication in spec because there are cases when the tests makes so dynamic that will be hard to debug
> Add Code Climate config file

- app/controllers/api/v1/api_controller.rb
- app/controllers/api/v1/sessions_controller.rb
- config/locales/en.yml
- spec/requests/api/v1/sessions/facebook_spec.rb
> Move strings to locals

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
> Add Github recommended community standards

- apiary.apib
This aims to improve the doc work in order to reuse the request/response payloads.
Check https://apiblueprint.org/documentation/mson/specification.html for more info
You can check https://railsapibase.docs.apiary.io/# for the preview
In the future, [Api Blueprint expects to make headers reusable](https://github.com/apiaryio/api-blueprint-rfcs/pull/3), so we don't have to repeat the auth headers every time.
> Use Attributes and Data structures in Api Blueprint

- .circleci/application.yml
- .circleci/config.yml
- .circleci/database.yml
- circle.yml
> Migrate Circle CI to v2

- config/initializers/carrierwave.rb
> Fix fog configuration

- .rubocop.yml
Following channel talk we disable this rule
> Disable use module_function instead of self rule

- app/controllers/api/concerns/act_as_api_request.rb
- spec/spec_helper.rb
> Fix #122 and #123

- Gemfile.lock
Forgot to bundle project on previous pr
> remove facebook from gemfile.lock

- app/controllers/api/concerns/act_as_api_request.rb
Fix issue with content-type text/html instead of application/json
> Fix content-type issue

- .circleci/config.yml
- .codeclimate.yml
- README.md
This PR includes:
* Configuration to enable test coverage in codeclimate
* Also it was added the new version of .codeclimate.yml
> add codeclimate

- .reek.yml
- db/seeds.rb
- spec/rails_helper.rb
In this PR:
- Removed `CIRCLE_ARTIFACTS` because we are now using CodeClimate to visualize code coverage.
- Remove old exclusion from `.reek.yml`
- Check if development environment when creating sample admin user in seeds.
> Several minor improvements

- .gitignore
- .rspec
- spec/models/user_spec.rb
- spec/requests/api/v1/passwords/create_spec.rb
- spec/requests/api/v1/passwords/edit_spec.rb
- spec/requests/api/v1/passwords/update_spec.rb
- spec/requests/api/v1/sessions/create_spec.rb
- spec/requests/api/v1/sessions/destroy_spec.rb
- spec/requests/api/v1/users/create_spec.rb
- spec/requests/api/v1/users/profile_spec.rb
- spec/requests/api/v1/users/show_spec.rb
- spec/requests/api/v1/users/update_spec.rb
- spec/routing/registrations_routing_spec.rb
- spec/routing/sessions_routing_spec.rb
- spec/routing/user_routing_spec.rb
Add --require rails_helper to a `.rspec` file in the project root. This has the effect that all the specs are automatically run with rails_helper pre-required.
> Require rails_helper from '.rspec'

- Gemfile
Idea from @juanmanuelramallo 
https://andycroll.com/ruby/use-loose-ruby-versioning-in-your-gemfile/
> Use loose ruby versioning

- README.md
This changeset groups database-related tasks on the README steps.
> Group Rake database tasks on README steps

- app/controllers/api/v1/settings_controller.rb
- app/models/setting.rb
- config/routes.rb
- db/migrate/20200128183708_add_must_update_fields.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/settings.rb
- spec/requests/api/v1/settings_spec.rb
https://github.com/rootstrap/rails_api_base/issues/165
- Add setting table with a key value structure to add needed configuration and further needed for other configurations
- Add initial min version needed as 0.0
- In case you need to update your version you can modify the db value and thats all
> [ISSUE-165] add force update endpoint

- .dockerignore
- Dockerfile
- README.md
- config/database.yml.example
- docker-compose.yml
The usage of Docker in any project is supposed to be **optional**
This PR adds the Dockerfile and docker-compose.yml files.
> Add Docker support

- yarn.lock
Fixes https://github.com/advisories/GHSA-6c8f-qphg-qjgp
> Upgrade kind-of

- app/controllers/api/v1/api_controller.rb
> Skip pundit authorization for status action

- .rubocop.yml
- Gemfile
- db/migrate/20200128183708_create_settings.rb
- db/seeds.rb
When starting a new project off this template we would want it to be clean of linter issues.
In this PR we fix all Rubocop issues.
- Excluding bin/bundle and bin/yarn from Rubocop given those were autogenerated
- Adding timestamps to settings table (migration filename is off fixing that too)
* Fix existing reek issues in a subsequent PR
> Fixing rubocop issues

- spec/decorators/user_decorator_spec.rb
- spec/factories/admin_users.rb
- spec/mailers/application_mailer_spec.rb
- spec/policies/admin_user_policy_spec.rb
- spec/rails_helper.rb
> improve coverage

- .github/ISSUE_TEMPLATE/bug_report.md
A simple template using the github template builder so the user can choose between a bug template or feature template
> Update issue bug templates

- .circleci/config.yml
Dependency caching was done on a different folder which I guess didn't even exist. Seems like a copy-paste from a python project. Anyway, this should speed build by ~2 minutes~ 4 minutes or so, also saving 💵 
---
*
---
---
*
---
**Before**
**After**
> Correctly cache bundler dependencies

- bin/auto_rspec
This allows running specs for the changed files by following some conventions. It's really handy on big projects TBH. The goal of this PR is to open a discussion, if approved we should ask permission from the author to add it.
---
*
---
---
*
---
> Add auto run for Rspec

- README.md
- references #238
---
Improve docker usage documentation.
> improve docker documentation in readme

- config/application.rb
Fixes an error `No route matches [POST] "/admin/users/1"` on record update
> Add rack method override middleware

- .circleci/config.yml
- lib/tasks/code_analysis.rake
The project has a rake task that didn't appear in list task
---
`bundle exec rails -T`
> More friendly rake code:analysis 

- README.md
Sorry reviewers 🙏 
I forgot to update README.md related to [PR 299](https://github.com/rootstrap/rails_api_base/pull/299)
> Update README.md related to PR 299

- README.md
* no ticket available
---
README update for rails 7
> Update README to rails 7.0

- config/environments/production.rb
When doing https://github.com/rootstrap/rails_api_base/pull/357 we left this wrong by mistake https://github.com/rootstrap/rails_api_base/pull/357/files/76c0a6f11c15764cebb13bc4c2981942f4e3f0ff#r966239405
thanks @andresg4 for detecting it
> Fix prod env

- .github/test_db/config/database.yml
- .github/workflows/ci.yml
- .gitignore
- bootstrap.sh
- config/database.yml
Remove `database.yml` from `.gitignore` file and update scripts.
Since the database file reads the values from environment variables, we can track it without reveal any confidencial information.
- Be able to start the api base project directly without any additional setup (mostly for development purpose).
- Simplify CI/CD setup
> Version database.yml file and update scripts

- .github/workflows/update_knapsack_report.yml
---
Fix Knapsack Report workflow
---
*
---
---
*
---
> fix Knapsack Report workflow

- .github/workflows/ci.yml
- .github/workflows/update_knapsack_report.yml
---
- Set the maximum number of minutes before it timeouts, the default value is 6 hours.
---
*
---
---
*
---
> Set CI timeout

- bin/helpers.rb
This pull request fixes the 'dotenv/load' in helpers.rb. This bug was discovered when deploying on Heroku and it results in an error.
---
*
---
---
*
---
> Hotfix dotenv load

- README.md
---
Update Codeclimate readme to use GitHub Actions instead of CircleCI
---
*
---
---
*
---
> update code climate readme

- README.md
* Adds the pretender gem to the `README.md` list and a section that warns about its use.
> [Impersonator] Readme Warning

- app/constraints/impersonation/enabled_constraint.rb
- config/routes.rb
Fixes running `rails db:drop db:create`
> Fix routes

- Gemfile.lock
> Upgrade `bundler` version to the latest one

- spec/rails_helper.rb
Since we upgraded rspec-rails the scaffolds generator got broken.
https://github.com/rspec/rspec-rails/pull/2751
> Fix Rails generators

- Gemfile.lock
> Remove white spaces from Gemfile.lock

- .gitignore
- heroku.yml
* [Ticket #NUMBER_OF_THE_TICKET](https://www.notion.so/rootstrap/One-off-Tasks-e7bed551a599475ea88f9c825c9cfdb7?p=24a4253f537c4617b73fbb8e5148ba1e&pm=s)
---
---
*
---
---
*
---
> Change heroku deployment to use the dockerfile

- docker-compose.test.yml
- docs/fullstack.md
---
- Added the `volume` to the `docker-compose.test.yml` so the changes from the `fullstack` script are applied to the local files and not only in the container
- Added `&& docker compose -f docker-compose.test.yml down` to the fullstack command in the docs so the `tests` container is stopped when it finishes running
---
*
---
---
*
---
> Adjust fullstack script with Docker

- docker-compose.yml
> Add volume for node_modules

- Dockerfile
- Dockerfile.dev
- docker-compose.yml
* [Ticket #NUMBER_OF_THE_TICKET](https://www.notion.so/rootstrap/One-off-Tasks-e7bed551a599475ea88f9c825c9cfdb7?p=866941cff01349f3af35d61f93e315e8&pm=s)
---
--- Checks for web and db were added, now on status we can chech if healthy or not
*
---
---
*
---
> Add health check on docker compose

- config/initializers/pagy.rb
Taken from https://ddnexus.github.io/pagy/quick-start/#2-configure
> Update pagy configs

- config/initializers/filter_parameter_logging.rb
- config/initializers/lograge.rb
TODO:
Notes:
- [semantic_logger](https://logger.rocketjob.io/rails.html) is definitively more powerful. But I'm not sure it's worth the effort, just the setup requires considering many things like Heroku, Puma, RSpec, etc
Sources:
- https://prefab.cloud/blog/rails-logging-gems-2024/
- https://betterstack.com/community/guides/logging/best-ruby-logging-libraries/
> Improve Lograge configs

- Dockerfile.dev
> [Fix-Dockerfile.dev] .ruby-version file is needed

- .github/workflows/ci.yml
> CI docker cache fix

- config/database.yml
---
Update pool size according to this [article](https://island94.org/2024/09/secret-to-rails-database-connection-pool-size)
*
---
---
*
---
> Update db connections pool size
